### ISSUE TITLE
checkpoint_dir？？

### ISSUE THREAD

**Issue by LegionHXF** [IdeGelis/torch-points3d-SiamKPConvVariants#3]
I am running the trainSiamKPConv.py file, and the error message shows that SiameseKPConvUnshared.pt in my checkpoint_dir is empty? How can I solve this problem?

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by LegionHXF** [comment]
Thank you for your answer, but this file can be downloaded but cannot be decompressed and opened?

**Comment by LegionHXF** [comment]
Thank you for your answer, but this file can be downloaded but cannot be decompressed and opened?

**Comment by IdeGelis** [comment]
Dear LegionHXF, 
Thank for the interest in my code. SiameseKPConvUnshared.pt is the unshared weight version of the Siamese network, also called Pseudo-Siamese KPConv in the publication, which I only recommand if the two input are of different types (see the publication [https://www.sciencedirect.com/science/article/abs/pii/S0924271623000394](https://www.sciencedirect.com/science/article/abs/pii/S0924271623000394) ) for more details.

The weights of the different networks trained on Urb3DCD dataset are available here : [https://filesender.renater.fr/?s=download&token=094e425b-c980-445e-ac9c-34f754056acc]( https://filesender.renater.fr/?s=download&token=094e425b-c980-445e-ac9c-34f754056acc)

Best regards,
Iris

**Comment by LegionHXF** [comment]
> Dear LegionHXF, Thank for the interest in my code. SiameseKPConvUnshared.pt is the unshared weight version of the Siamese network, also called Pseudo-Siamese KPConv in the publication, which I only recommand if the two input are of different types (see the publication https://www.sciencedirect.com/science/article/abs/pii/S0924271623000394 ) for more details.
> 
> The weights of the different networks trained on Urb3DCD dataset are available here : https://filesender.renater.fr/?s=download&token=094e425b-c980-445e-ac9c-34f754056acc
> 
> Best regards, Iris

Hello, my disk is damaged and the permission-heavy file is lost. Can you reopen the link [service]( https://filesender.renater.fr/?s=download&token=094e425b-c980-445e-ac9c-34f754056acc) for the permission-heavy file? Thank you.

**Comment by IdeGelis** [comment]
Hello,
The link is still open until the 16th of November. I don't understand, what do you want me to do ? 

Best regards,
Iris

**Comment by LegionHXF** [comment]
Thank you for your answer. There is a problem with my network.problem has been solved。





> Hello, The link is still open until the 16th of November. I don't understand, what do you want me to do ?
> 
> Best regards, Iris
